In [ ]:
"""
Equality
To check if two Python values, or variables, are equal you can use ==. To check for inequality, you need !=. As a refresher, have a look at the following examples that all result in True. Feel free to try them out.

2 == (1 + 1)
"intermediate" != "python"
True != False
"Python" != "python"
When you write these comparisons in a script, you will need to wrap a print() function around them to see the output.

Instructions
Write code to see if True equals False.
Write Python code to check if -5 * 15 is not equal to 75.
Ask Python whether the strings "pyscript" and "PyScript" are equal.
What happens if you compare booleans and integers? Write code to see if True and 1 are equal.
"""

In [4]:
# Comparison of booleans
True == False

# Comparison of integers
-5 * 15 != 75

# Comparison of strings
"pyscript" == "PyScript"

# Compare a boolean with an integer
True == 1

True

In [ ]:
"""
Greater and less than
In the video, Hugo also talked about the less than and greater than signs, < and > in Python. You can combine them with an equals sign: <= and >=. Pay attention: <= is valid syntax, but =< is not.

All Python expressions in the following code chunk evaluate to True:

3 < 4
3 <= 4
"alpha" <= "beta"
Remember that for string comparison, Python determines the relationship based on alphabetical order.

Instructions

Write Python expressions, wrapped in a print() function, to check whether:
x is greater than or equal to -10. x has already been defined for you.
"test" is less than or equal to y. y has already been defined for you.
True is greater than False.
"""

In [ ]:
# Comparison of integers
x = -3 * 6
print(x >= -10)

# Comparison of strings
y = "test"
print('test' <= y)

# Comparison of booleans
print(True > False)

False
True
True


In [8]:
"""
Compare arrays
Out of the box, you can also use comparison operators with NumPy arrays.

Remember areas, the list of area measurements for different rooms in your house from Introduction to Python? This time there's two NumPy arrays: my_house and your_house. They both contain the areas for the kitchen, living room, bedroom and bathroom in the same order, so you can compare them.

Instructions
Using comparison operators, generate boolean arrays that answer the following questions:

Which areas in my_house are greater than or equal to 18?
You can also compare two NumPy arrays element-wise. Which areas in my_house are smaller than the ones in your_house?
Make sure to wrap both commands in a print() statement so that you can inspect the output!
"""

# Create arrays
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

In [9]:
my_house > 18

array([False,  True, False, False])

In [ ]:
# my_house greater than or equal to 18
print(my_house >= 18)

# my_house less than your_house
print(my_house < your_house)


[False  True False False]
[False  True  True False]


In [ ]:
"""
and, or, not (1)
A boolean is either 1 or 0, True or False. With boolean operators such as and, or and not, you can combine these booleans to perform more advanced queries on your data.

In the sample code, two variables are defined: my_kitchen and your_kitchen, representing areas.

Instructions
Write Python expressions, wrapped in a print() function, to check whether:
my_kitchen is bigger than 10 and smaller than 18.
my_kitchen is smaller than 14 or bigger than 17.
double the area of my_kitchen is smaller than triple the area of your_kitchen.
"""

In [3]:
# Define variables
my_kitchen = 18.0
your_kitchen = 14.0

# my_kitchen bigger than 10 and smaller than 18?
print(my_kitchen > 10 and my_kitchen < 18)

# my_kitchen smaller than 14 or bigger than 17?
print(my_kitchen > 17 or my_kitchen < 14)

# Double my_kitchen smaller than triple your_kitchen?
print(my_kitchen * 2 < your_kitchen * 3)

False
True
True


In [4]:
x = 8
y = 9
not(not(x < 3) and not(y > 14 or y > 10))

False

In [ ]:
import numpy as np

"""
Boolean operators with NumPy
Before, the operational operators like < and >= worked with NumPy arrays out of the box. Unfortunately, this is not true for the boolean operators and, or, and not.

To use these operators with NumPy, you will need np.logical_and(), np.logical_or() and np.logical_not(). Here's an example on the my_house and your_house arrays from before to give you an idea...

Instructions
Generate boolean arrays that answer the following questions:
Which areas in my_house are greater than 18.5 or smaller than 10?
Which areas are smaller than 11 in both my_house and your_house? Make sure to wrap both commands in print() statement, so that you can inspect the output.
"""

my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

np.logical_and(my_house > 13, your_house < 15)

array([ True, False, False, False])

In [ ]:
# my_house greater than 18.5 or smaller than 10
print(np.logical_or(my_house > 18.5, my_house < 10))

# Both my_house and your_house smaller than 11
print(np.logical_and(my_house < 11, your_house < 11))

[False False False False]
[False False False  True]


In [11]:
area = 10.0
if(area < 9) :
    print("small")
elif(area < 12) :
    print("medium")
else :
    print("large")

medium


In [ ]:
"""
if
It's time to take a closer look around in your house.

Two variables are defined in the sample code: room, a string that tells you which room of the house we're looking at, and area, the area of that room.

Instructions
Examine the if statement that prints out "looking around in the kitchen." if room equals "kit".
Write another if statement that prints out "big place!" if area is greater than 15.
"""

In [12]:
# Define variables
room = "kit"
area = 14.0

# if statement for room
if room == "kit" :
    print("looking around in the kitchen.")

# if statement for area
if area > 15:
    print("big place!")

looking around in the kitchen.


In [ ]:
"""
Add else
In the script, the if construct for room has been extended with an else statement so that "looking around elsewhere." is printed if the condition room == "kit" evaluates to False.

Can you do a similar thing to add more functionality to the if construct for area?

Instructions
Add an else statement to the second control structure so that "pretty small." is printed out if area > 15 evaluates to False.
"""

In [13]:
# Define variables
room = "kit"
area = 14.0

# if-else construct for room
if room == "kit" :
    print("looking around in the kitchen.")
else :
    print("looking around elsewhere.")

# if-else construct for area
if area > 15 :
    print("big place!")
else:
    print("pretty small.")

looking around in the kitchen.
pretty small.


In [ ]:
"""
Customize further: elif
It's also possible to have a look around in the bedroom. The sample code contains an elif part that checks if room equals "bed". In that case, "looking around in the bedroom." is printed out.

It's up to you now! Make a similar addition to the second control structure to further customize the messages for different values of area.

Instructions
Add an elif to the second control structure such that "medium size, nice!" is printed out if area is greater than 10.
"""

In [14]:
# Define variables
room = "bed"
area = 14.0

# if-elif-else construct for room
if room == "kit" :
    print("looking around in the kitchen.")
elif room == "bed":
    print("looking around in the bedroom.")
else :
    print("looking around elsewhere.")

# if-elif-else construct for area
if area > 15 :
    print("big place!")
elif area > 10:
    print("medium size, nice!")
else :
    print("pretty small.")

looking around in the bedroom.
medium size, nice!


In [30]:
%%HTML

<h3><font>Basic while loop</font></h3>

<p>
Below you can find the example from the video where the <code>error</code> variable, initially equal to <code>50.0</code>, is divided by 4 and printed out on every run: <br>

<pre><code>
error = 50.0 
while error > 1 : 
    error = error / 4 
    print(error) 
</pre></code>

This example will come in handy, because it's time to build a <code>while</code> loop yourself! We're going to code a <code>while</code> loop that implements a very basic control system for an <font color=Blue>inverted pendulum</font>. If there's an offset from standing perfectly straight, the while loop will incrementally fix this offset.<br><br>

<b>Note that if your while loop takes too long to run, or your session is expiring, you might have created an infinite loop</b>. In particular, remember to <b>indent</b> the contents of the loop using four spaces or auto-indentation, and make sure the conditions are such that the loop has a stopping point.
</p>

<p>
<h4>Instructions</h4>
<ul>
    <li> Create the variable <code>offset</code> with an initial value of <code>8</code>. </li>
    <li> Code a <code>while</code> loop that keeps running as long as <code>offset</code> is not equal to <code>0</code>. Inside the <code>while</code> loop:
        <ul>
        <li> Print out the sentence "correcting...".</li>
        <li> Next, decrease the value of <code>offset</code> by 1. You can do this with <code>offset = offset - 1</code>.</li>
        <li> Finally, still within your loop, print out <code>offset</code> so you can see how it changes.</li>
    </ul>
</ul>
</p>

In [ ]:
# Initialize offset
offset = 8

# Code the while loop
while offset != 0:
    print('correcting...')
    offset -= 1
    print(offset)

correcting...
7
correcting...
6
correcting...
5
correcting...
4
correcting...
3
correcting...
2
correcting...
1
correcting...
0


In [ ]:
"""
Add conditionals
The while loop that corrects the offset is a good start, but what if offset is negative? You can try to run the following code where offset is initialized to -6:

# Initialize offset
offset = -6

# Code the while loop
while offset != 0 :
    print("correcting...")
    offset = offset - 1
    print(offset)
but your session will be disconnected. The while loop will never stop running, because offset will be further decreased on every run. offset != 0 will never become False and the while loop continues forever.

Fix things by putting an if-else statement inside the while loop.

Note that if your while loop takes too long to run, or your session is expiring, you might have created an infinite loop. In particular, remember to indent the contents of the loop using four spaces or auto-indentation, and make sure the conditions are such that the loop has a stopping point.

Instructions
Initialize offset to -6.
Inside the while loop, complete the if-else statement:
If offset is greater than zero, you should decrease offset by 1.
Else, you should increase offset by 1.
If your code is taking too long to run (or your session is expiring), you probably made a mistake. Check your code and make sure that the statement offset != 0 will eventually evaluate to FALSE!
"""

In [32]:
# Initialize offset
offset = -6

# Code the while loop
while offset != 0 :
    print("correcting...")
    if offset > 0:
      offset -= 1
    else : 
      offset += 1
    print(offset)

correcting...
-5
correcting...
-4
correcting...
-3
correcting...
-2
correcting...
-1
correcting...
0


In [33]:
height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
weight = np.array([65.4, 59.2, 63.6, 88.4, 68.47])

bmi = weight / height ** 2
for val in bmi:
    print(val)

21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.36949533410318


In [37]:
meas = np.array([height, weight])

print(meas)
for val in np.nditer(meas):
    print(val)

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.47]]
1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.47
